backend:
  name: github
  repo: water9626/download-web
  branch: main
media_library:
  name: github
  folder: /static/uploads
collections:
  - name: products
    label: 产品
    folder: /content/products
    create: true
    slug: '{{title}}'
    fields:
      - { label: "产品名称", name: "title", widget: "string" }
      - { label: "简介", name: "desc", widget: "text" }
      - { label: "价格", name: "price", widget: "string" }
      - { label: "产品图片", name: "image", widget: "image" }
